/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    user: User;
    Products: Product;
    AnotherInfo: AnotherInfo;
    media: Media;
    HomePage: HomePage;
    'banner-media': BannerMedia;
    'about-us': AboutUs;
    users: User1;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
}
export interface Product {
  id: string;
  isDeposit?: boolean | null;
  Car_Name?: string | null;
  Car_Brand: string;
  Car_Type?: string | null;
  Car_Color:
    | 'red'
    | 'orange_color'
    | 'orange'
    | 'yellow'
    | 'gold'
    | 'brown'
    | 'green'
    | 'blue'
    | 'indigo'
    | 'violet'
    | 'gray'
    | 'sliver'
    | 'black'
    | 'white';
  Car_CC: number;
  Car_Year: number;
  Car_Mileage: number;
  Engin_fuel: string;
  Car_Transmission: string;
  Car_Info?:
    | {
        relationTo: 'AnotherInfo';
        value: string | AnotherInfo;
      }[]
    | null;
  Car_OtherInfo?:
    | {
        Car_Title?: string | null;
        Car_Remark?: string | null;
        id?: string | null;
      }[]
    | null;
  price?: number | null;
  PriceFormatText?: string | null;
  is_onSale?: boolean | null;
  onSale?: number | null;
  OnSaleFormatText?: string | null;
  car_status?: ('new-vehicle' | 'recommend-vehicle' | 'onSale-vehicle' | 'vehicle') | null;
  status: 'sell' | 'preview';
  images: {
    car_picture: string | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface AnotherInfo {
  id: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface HomePage {
  id: string;
  bannerArray?:
    | {
        banner: string | BannerMedia;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface BannerMedia {
  id: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface AboutUs {
  id: string;
  title?: string | null;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface User1 {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User1;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}